server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 # 不限制请求体的大小

spring:
  application:
    name: ai-interviewer
  profiles:
    active: dev # dev 开发环境，prod 生产环境，test 测试环境

# 日志级别
logging:
  level:
    root: info
